use crate::{checked_u64_add, Error, Result};

/// Decoder and evaluator limits.  Every limit is archive-controlled only in
/// the sense that the archive is rejected when it asks for more; an archive
/// can never raise these values.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Limits {
    pub max_archive_bytes: u64,
    pub max_output_bytes: u64,
    pub max_block_payload_bytes: u64,
    pub max_block_output_bytes: u64,
    pub max_definitions: u64,
    pub max_nodes: u64,
    pub max_edges: u64,
    pub max_graph_depth: u64,
    pub max_fan_out: u64,
    pub max_node_payload_bytes: u64,
    pub max_parameter_bytes: u64,
    pub max_pattern_bytes: u64,
    pub max_recurrence_order: u64,
    pub max_generated_bytes: u64,
    pub max_temporary_bytes: u64,
    pub max_work: u64,
    pub max_parameter_delta_abs: u64,
}

impl Default for Limits {
    fn default() -> Self {
        Self {
            // Whole-file limits are deployment policy; block limits below are
            // frozen container-v1 hard bounds.
            max_archive_bytes: 1 << 40,
            max_output_bytes: 1 << 40,
            max_block_payload_bytes: 1 << 25,
            max_block_output_bytes: 1 << 24,
            max_definitions: 1 << 18,
            max_nodes: 1 << 20,
            max_edges: 1 << 21,
            max_graph_depth: 256,
            max_fan_out: 1 << 16,
            max_node_payload_bytes: 1 << 25,
            max_parameter_bytes: 1 << 24,
            max_pattern_bytes: 1 << 24,
            max_recurrence_order: 1 << 14,
            max_generated_bytes: 1 << 34,
            max_temporary_bytes: 1 << 26,
            max_work: 1 << 40,
            max_parameter_delta_abs: 1 << 31,
        }
    }
}

impl Limits {
    pub fn check(&self, what: &'static str, actual: u64, limit: u64) -> Result<()> {
        if actual > limit {
            Err(Error::LimitExceeded {
                what,
                actual,
                limit,
            })
        } else {
            Ok(())
        }
    }
}

/// Checked counters used during structural validation and evaluator preflight.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Usage {
    pub nodes: u64,
    pub edges: u64,
    pub work: u64,
    pub generated_bytes: u64,
    pub temporary_bytes_peak: u64,
}

impl Usage {
    pub fn charge_nodes(&mut self, amount: u64, limits: &Limits) -> Result<()> {
        self.nodes = checked_u64_add(self.nodes, amount, "node usage")?;
        limits.check("nodes", self.nodes, limits.max_nodes)
    }

    pub fn charge_edges(&mut self, amount: u64, limits: &Limits) -> Result<()> {
        self.edges = checked_u64_add(self.edges, amount, "edge usage")?;
        limits.check("edges", self.edges, limits.max_edges)
    }

    pub fn charge_work(&mut self, amount: u64, limits: &Limits) -> Result<()> {
        self.work = checked_u64_add(self.work, amount, "work usage")?;
        limits.check("work", self.work, limits.max_work)
    }

    pub fn charge_generated(&mut self, amount: u64, limits: &Limits) -> Result<()> {
        self.generated_bytes = checked_u64_add(self.generated_bytes, amount, "generated bytes")?;
        limits.check(
            "generated bytes",
            self.generated_bytes,
            limits.max_generated_bytes,
        )
    }

    pub fn observe_temporary(&mut self, amount: u64, limits: &Limits) -> Result<()> {
        self.temporary_bytes_peak = self.temporary_bytes_peak.max(amount);
        limits.check(
            "temporary bytes",
            self.temporary_bytes_peak,
            limits.max_temporary_bytes,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn usage_rejects_the_first_excess_deterministically() {
        let limits = Limits {
            max_nodes: 2,
            max_edges: 3,
            max_work: 5,
            max_generated_bytes: 7,
            max_temporary_bytes: 11,
            ..Limits::default()
        };
        let mut usage = Usage::default();
        usage.charge_nodes(2, &limits).unwrap();
        assert!(matches!(
            usage.charge_nodes(1, &limits),
            Err(Error::LimitExceeded { what: "nodes", .. })
        ));
        usage.charge_edges(3, &limits).unwrap();
        usage.charge_work(5, &limits).unwrap();
        usage.charge_generated(7, &limits).unwrap();
        usage.observe_temporary(11, &limits).unwrap();
    }

    #[test]
    fn defaults_include_the_frozen_v1_block_hard_bounds() {
        let limits = Limits::default();
        assert_eq!(limits.max_block_output_bytes, 16 * 1024 * 1024);
        assert_eq!(limits.max_block_payload_bytes, 32 * 1024 * 1024);
        assert_eq!(limits.max_definitions, 262_144);
        assert_eq!(limits.max_nodes, 1_048_576);
        assert_eq!(limits.max_edges, 2_097_152);
        assert_eq!(limits.max_graph_depth, 256);
        assert_eq!(limits.max_temporary_bytes, 64 * 1024 * 1024);
        assert_eq!(limits.max_work, 1u64 << 40);
    }
}
